fix: deprecate
ThePrimeagen/git-worktree.nvim pull request #2
Opened 2021-04-02 16:20 UTC by tjdevries

Fix: #1

2021-04-02 16:24 UTC, Sparkenstein approved these changes

2021-04-02 16:28 UTC, drodger commented
I'm so glad someone took the time to fork this project before it's too late! It's always sad when the original developer stops caring...

2021-04-02 16:29 UTC, Herz3h commented
saved

2021-04-02 16:49 UTC, frandsoh requested changes
Fix wording

2021-04-02 16:49 UTC, frandsoh commented on README.md
> +NOTE: This project has been abandonded. Looking for maintainers!
Fix wording

```suggestion
NOTE: This project has been shamelessly abandonded and left to die by @ThePrimeagen . Looking for maintainers!
```

2021-04-02 16:58 UTC, frandsoh approved these changes

2021-04-02 20:15 UTC, RichardMcSorley commented
LGTM

![Joey nice](https://media.giphy.com/media/ftYpwfV6ZcerEa8poV/giphy.gif)

2021-04-03 00:23 UTC, eruizc-dev approved these changes
- [x] Make by TJ
 - [x] Looks professional
 - [x] It's clear
 - [x] Looks professional
 - [x] Made by TJ
I approve

2021-04-03 02:07 UTC, RichardMcSorley approved these changes

2021-04-03 02:50 UTC, ThePrimeagen commented
Telescopic "cash" Johnson, could you please resolve conflicts.

2021-04-03 03:20 UTC, RichardMcSorley commented
![poggers](https://emoji.gg/assets/emoji/PoggersRow.gif) ![poggers](https://emoji.gg/assets/emoji/PoggersRow.gif) ![poggers](https://emoji.gg/assets/emoji/PoggersRow.gif) ![poggers](https://emoji.gg/assets/emoji/PoggersRow.gif) ![poggers](https://emoji.gg/assets/emoji/PoggersRow.gif) ![poggers](https://emoji.gg/assets/emoji/PoggersRow.gif)

2021-04-09 18:06 UTC, ThePrimeagen commented
ok jokes over babes

2021-04-09 18:06 UTC, closed without merging